/*
 * app_config.h
 *
 *  Created on: Jun 2, 2026
 *      Author: yuan
 */

#ifndef INC_APP_CONFIG_H_
#define INC_APP_CONFIG_H_

#define APP_ADC_FILTERED_ABS_MAX 4095
#define APP_TARGET_SPEED_MAX 1000
#define APP_FILTERED_ALPHA 0.2
#define APP_PID_OUTPUT_MAX 1000.0
#define MOTOR_PWM_ABS_MAX  1000.0
#define MOTOR_PWM_THRESHOLD 980
#define APP_SPEED_ABS_LIMIT 2000
#define APP_ENCODER_LOST_CHECK_TARGET 100
#define APP_ENCODER_LOST_CHECK_EPS 5
#define APP_ENCODER_LOST_TICK 50
#define APP_MOTOR_PWM_SATURATION_TICK 80
#define APP_CONTROL_DT_SEC 0.01
#define APP_CONTROL_PERIOD_MS 10
#define APP_UART_LINE_SIZE 100
#define APP_UART_TX_SIZE 160
#define APP_UART_RX_IDLE_CHUNK_SIZE 32
#define APP_UART_RX_RING_SIZE 128
#define APP_TARGET_SPEED_MIN 0
#define APP_ENCODER_COUNTER_PER_REV 28.0f
#define APP_ENCODER_SPEED_AVG_N 5
#define APP_PID_DEFAULT_KP 0.0f
#define APP_PID_DEFAULT_KI 0.0f
#define APP_PID_DEFAULT_KD 0.0f
#define APP_PWM_FF_KS 66.0f
#define APP_PWM_FF_KV 0.12f
#define APP_PWM_START_BOOST 900
#define APP_PWM_START_BOOST_TICK 10
#define APP_ADC_CH_COUNT 2
#define APP_LOG_TICK 3000
#endif /* INC_APP_CONFIG_H_ */
